from __future__ import annotations


FLUX2_KLEIN_STEPS = 4

QWEN_2511_LIGHTNING_DEFAULT_STEPS = 8
QWEN_2511_LIGHTNING_DEFAULT_GUIDANCE = 1.0
QWEN_2511_BASE_DEFAULT_STEPS = 40
QWEN_2511_BASE_DEFAULT_GUIDANCE = 4.0

HIDREAM_DEFAULT_STEPS = 40
HIDREAM_DEFAULT_GUIDANCE = 5.0

BOOGU_DEFAULT_STEPS = 4
BOOGU_DEFAULT_GUIDANCE = 1.0
